# Generated by Django 5.0.6 on 2024-06-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsmodel",
            old_name="description1_ru",
            new_name="description_ru",
        ),
        migrations.RenameField(
            model_name="newsmodel",
            old_name="description1_uz",
            new_name="description_uz",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="description2_ru",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="description2_uz",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="description3_ru",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="description3_uz",
        ),
    ]
