# Generated by Django 5.0.6 on 2024-06-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0002_rename_description1_ru_newsmodel_description_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsmodel",
            name="author",
        ),
    ]
