# Generated by Django 5.0.6 on 2024-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=255)),
                ("familiya", models.CharField(max_length=255)),
                ("tel", models.CharField(max_length=20)),
                ("sana", models.DateField()),
                ("sms", models.TextField(blank=True, null=True)),
                (
                    "fayl",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/messages/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "message",
                "ordering": ["-sana"],
                "indexes": [
                    models.Index(fields=["ism"], name="message_ism_fe6c69_idx"),
                    models.Index(
                        fields=["familiya"], name="message_familiy_32d0ff_idx"
                    ),
                    models.Index(fields=["tel"], name="message_tel_0c67f1_idx"),
                ],
            },
        ),
    ]
