# Generated by Django 5.0.6 on 2024-05-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Doctor Category",
                "verbose_name_plural": "DoctorCategory",
                "db_table": "doctorcategory",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="media/image")),
                ("specialty_uz", models.CharField(max_length=255)),
                ("specialty_ru", models.CharField(max_length=255)),
                ("vedio", models.URLField(blank=True, null=True)),
                ("education", models.CharField(max_length=255)),
                (
                    "experience1_uz",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience1_ru",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience2_uz",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience2_ru",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience3_uz",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience3_ru",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience4_uz",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience4_ru",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_doctor.doctorcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctor",
            },
        ),
    ]
