# Generated by Django 5.0.6 on 2024-05-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_department",
            "0002_alter_department_options_remove_department_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="category_ru",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments_ru",
                to="app_department.departmentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="category_uz",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments_uz",
                to="app_department.departmentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description1_ru",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description1_uz",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_ru",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_uz",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_ru",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_uz",
            field=models.CharField(blank=True, default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_cafedra_ru",
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_cafedra_uz",
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_ru",
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_uz",
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="vedio",
            field=models.URLField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name="departmentcategory",
            name="category_name_ru",
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name="departmentcategory",
            name="category_name_uz",
            field=models.CharField(default=2, max_length=255),
        ),
    ]
