# Generated by Django 5.0.6 on 2024-05-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_department", "0005_remove_department_category_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="category_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments_uz",
                to="app_department.departmentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description1_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description1_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_cafedra_ru",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_cafedra_uz",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_ru",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_uz",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="vedio",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="departmentcategory",
            name="category_name",
            field=models.CharField(max_length=255),
        ),
    ]
