# Generated by Django 5.0.6 on 2024-06-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_department", "0006_alter_department_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="name_cafedra_ru",
        ),
        migrations.RemoveField(
            model_name="department",
            name="name_cafedra_uz",
        ),
    ]
