# Generated by Django 5.0.6 on 2024-06-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_department", "0007_remove_department_name_cafedra_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="category_name",
        ),
        migrations.DeleteModel(
            name="DepartmentCategory",
        ),
    ]
