# Generated by Django 5.0.6 on 2024-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_department", "0008_remove_department_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="operation1_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation1_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation2_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation2_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation3_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation3_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation4_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="operation4_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
