# Generated by Django 5.0.6 on 2024-07-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_department",
            "0009_department_operation1_ru_department_operation1_uz_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description1_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description1_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description2_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description3_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation1_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation1_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation2_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation2_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation3_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation3_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation4_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="operation4_uz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
